/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/avaturn-t2.glb -o src/components/Model.jsx 
*/

import React from 'react'
import { useFrame, useGraph } from '@react-three/fiber'
import { useAnimations, useGLTF } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from 'three'
import { useChat } from '../hooks/useChat'

const corresponding = {
  A: 'viseme_PP',
  B: 'viseme_kk',
  C: 'viseme_I',
  D: 'viseme_AA',
  E: 'viseme_O',
  F: 'viseme_U',
  G: 'viseme_FF',
  H: 'viseme_TH',
  X: 'viseme_PP',
}

function filterClipForHumanoid(clip) {
  const filteredTracks = clip.tracks.filter((track) => {
    const name = track.name
    return name.endsWith('Hips.position') || name.endsWith('.quaternion')
  })
  return new THREE.AnimationClip(clip.name, clip.duration, filteredTracks)
}

function setMorphValue(meshes, morphName, value, speed = 0.25) {
  for (const mesh of meshes) {
    const dict = mesh.morphTargetDictionary
    const infl = mesh.morphTargetInfluences
    if (!dict || !infl) continue
    const idx = dict[morphName]
    if (idx === undefined) continue
    infl[idx] = THREE.MathUtils.lerp(infl[idx], value, speed)
  }
}

export function Model(props) {
  const { scene } = useGLTF('/models/avaturn-t2.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)

  const group = React.useRef()
  const { animations: externalAnimations = [] } = useGLTF('/models/animations.glb')
  const animations = React.useMemo(() => externalAnimations.map(filterClipForHumanoid), [externalAnimations])
  const { actions, mixer } = useAnimations(animations, group)

  const { message, onMessagePlayed, audioUnlocked } = useChat()
  const [lipsync, setLipsync] = React.useState(null)
  const [animation, setAnimation] = React.useState(() => {
    if (!animations?.length) return 'Idle'
    return animations.find((a) => a.name === 'Idle') ? 'Idle' : animations[0].name
  })

  const morphMeshes = React.useMemo(() => {
    const meshes = []
    clone.traverse((obj) => {
      if (obj?.isSkinnedMesh && obj.morphTargetDictionary && obj.morphTargetInfluences) meshes.push(obj)
    })
    return meshes
  }, [clone])

  const blinkRef = React.useRef(0) // 0..1
  const nextBlinkAtRef = React.useRef(0)

  React.useEffect(() => {
    // schedule first blink
    nextBlinkAtRef.current = performance.now() + 500 + Math.random() * 1500
  }, [])

  React.useEffect(() => {
    let morphTargets = 0
    let jawName = null

    clone.traverse((obj) => {
      if (obj?.isSkinnedMesh && obj.morphTargetDictionary) {
        morphTargets += Object.keys(obj.morphTargetDictionary).length
      }
      if (!jawName && obj?.isBone && typeof obj.name === 'string' && /jaw/i.test(obj.name)) {
        jawName = obj.name
      }
    })

    console.log('[Model] morphTargets count:', morphTargets)
    console.log('[Model] jaw bone:', jawName || '<not found>')
  }, [clone])

  React.useEffect(() => {
    if (!message) {
      setAnimation(animations?.find((a) => a.name === 'Idle') ? 'Idle' : animations?.[0]?.name || 'Idle')
      setLipsync(null)
      return
    }

    if (message.animation) setAnimation(message.animation)
    setLipsync(message.lipsync || null)
  }, [message, animations])

  React.useEffect(() => {
    if (!actions || !animation) return
    const action = actions[animation]
    if (!action) return

    action.reset().fadeIn(mixer?._actions?.length ? 0.5 : 0).play()
    return () => action.fadeOut(0.5)
  }, [actions, animation, mixer])

  React.useEffect(() => {
    if (!message?.audio) return
    if (!props?.audioRef?.current) return

    const audioBlob = new Blob([Uint8Array.from(atob(message.audio), (c) => c.charCodeAt(0))], { type: 'audio/mp3' })
    const audioURL = URL.createObjectURL(audioBlob)

    const audio = props.audioRef.current
    audio.src = audioURL
    audio.onended = () => {
      URL.revokeObjectURL(audioURL)
      onMessagePlayed?.()
    }

    const tryPlay = async () => {
      try {
        await audio.play()
        localStorage.setItem('audioUnlocked', 'true')
      } catch {
        const unlock = async () => {
          try {
            await audio.play()
            localStorage.setItem('audioUnlocked', 'true')
          } finally {
            window.removeEventListener('click', unlock)
          }
        }
        window.addEventListener('click', unlock, { once: true })
      }
    }

    if (audioUnlocked) void tryPlay()
  }, [message, onMessagePlayed, audioUnlocked, props?.audioRef])

  useFrame(() => {
    const audio = props?.audioRef?.current
    if (!audio || !lipsync?.mouthCues?.length) return
    if (!morphMeshes.length) return

    const t = audio.currentTime ?? 0
    let activeTarget = null
    for (let i = 0; i < lipsync.mouthCues.length; i++) {
      const cue = lipsync.mouthCues[i]
      if (t >= cue.start && t <= cue.end) {
        activeTarget = corresponding[cue.value] || null
        break
      }
    }

    for (const mesh of morphMeshes) {
      const dict = mesh.morphTargetDictionary
      const infl = mesh.morphTargetInfluences
      if (!dict || !infl) continue

      for (const targetName of Object.values(corresponding)) {
        const idx = dict[targetName]
        if (idx === undefined) continue
        infl[idx] = THREE.MathUtils.lerp(infl[idx], activeTarget === targetName ? 1 : 0, 0.25)
      }
    }
  })

  useFrame(() => {
    if (!morphMeshes.length) return

    const now = performance.now()
    const blinkNameL = 'eyeBlinkLeft'
    const blinkNameR = 'eyeBlinkRight'

    // trigger a blink periodically
    if (now >= nextBlinkAtRef.current) {
      // blink up quickly then down
      blinkRef.current = 1
      nextBlinkAtRef.current = now + 2500 + Math.random() * 2500
    }

    // decay blink back to 0 smoothly
    blinkRef.current = THREE.MathUtils.lerp(blinkRef.current, 0, 0.25)

    setMorphValue(morphMeshes, blinkNameL, blinkRef.current, 0.5)
    setMorphValue(morphMeshes, blinkNameR, blinkRef.current, 0.5)
  })

  return (
    <group ref={group} {...props} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh geometry={nodes.Body_Mesh.geometry} material={materials.Body} skeleton={nodes.Body_Mesh.skeleton} />
      <skinnedMesh geometry={nodes.avaturn_glasses_0.geometry} material={materials.avaturn_glasses_0_material} skeleton={nodes.avaturn_glasses_0.skeleton} />
      <skinnedMesh geometry={nodes.avaturn_glasses_1.geometry} material={materials.avaturn_glasses_1_material} skeleton={nodes.avaturn_glasses_1.skeleton} />
      <skinnedMesh geometry={nodes.avaturn_hair_0.geometry} material={materials.avaturn_hair_0_material} skeleton={nodes.avaturn_hair_0.skeleton} />
      <skinnedMesh geometry={nodes.avaturn_hair_1.geometry} material={materials.avaturn_hair_1_material} skeleton={nodes.avaturn_hair_1.skeleton} />
      <skinnedMesh geometry={nodes.avaturn_shoes_0.geometry} material={materials.avaturn_shoes_0_material} skeleton={nodes.avaturn_shoes_0.skeleton} />
      <skinnedMesh geometry={nodes.avaturn_look_0.geometry} material={materials.avaturn_look_0_material} skeleton={nodes.avaturn_look_0.skeleton} />
      <skinnedMesh name="Eye_Mesh" geometry={nodes.Eye_Mesh.geometry} material={materials.Eyes} skeleton={nodes.Eye_Mesh.skeleton} morphTargetDictionary={nodes.Eye_Mesh.morphTargetDictionary} morphTargetInfluences={nodes.Eye_Mesh.morphTargetInfluences} />
      <skinnedMesh name="EyeAO_Mesh" geometry={nodes.EyeAO_Mesh.geometry} material={materials.EyeAO} skeleton={nodes.EyeAO_Mesh.skeleton} morphTargetDictionary={nodes.EyeAO_Mesh.morphTargetDictionary} morphTargetInfluences={nodes.EyeAO_Mesh.morphTargetInfluences} />
      <skinnedMesh name="Eyelash_Mesh" geometry={nodes.Eyelash_Mesh.geometry} material={materials.Eyelash} skeleton={nodes.Eyelash_Mesh.skeleton} morphTargetDictionary={nodes.Eyelash_Mesh.morphTargetDictionary} morphTargetInfluences={nodes.Eyelash_Mesh.morphTargetInfluences} />
      <skinnedMesh name="Head_Mesh" geometry={nodes.Head_Mesh.geometry} material={materials.Head} skeleton={nodes.Head_Mesh.skeleton} morphTargetDictionary={nodes.Head_Mesh.morphTargetDictionary} morphTargetInfluences={nodes.Head_Mesh.morphTargetInfluences} />
      <skinnedMesh name="Teeth_Mesh" geometry={nodes.Teeth_Mesh.geometry} material={materials.Teeth} skeleton={nodes.Teeth_Mesh.skeleton} morphTargetDictionary={nodes.Teeth_Mesh.morphTargetDictionary} morphTargetInfluences={nodes.Teeth_Mesh.morphTargetInfluences} />
      <skinnedMesh name="Tongue_Mesh" geometry={nodes.Tongue_Mesh.geometry} material={materials.Teeth} skeleton={nodes.Tongue_Mesh.skeleton} morphTargetDictionary={nodes.Tongue_Mesh.morphTargetDictionary} morphTargetInfluences={nodes.Tongue_Mesh.morphTargetInfluences} />
    </group>
  )
}

useGLTF.preload('/models/avaturn-t2.glb')
useGLTF.preload('/models/animations.glb')

export default Model
