/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/model.glb 
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { button, useControls } from "leva";
import React, { useEffect, useRef, useState } from "react";

import * as THREE from "three";
import { useChat } from "../hooks/useChat";

const facialExpressions = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.1700000727403593,
    noseSneerRight: 0.14000002836874015,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41000000000000003,
  },
  funnyFace: {
    jawLeft: 0.63,
    mouthPucker: 0.53,
    noseSneerLeft: 1,
    noseSneerRight: 0.39,
    mouthLeft: 1,
    eyeLookUpLeft: 1,
    eyeLookUpRight: 1,
    cheekPuff: 0.9999924982764238,
    mouthDimpleLeft: 0.414743888682652,
    mouthRollLower: 0.32,
    mouthSmileLeft: 0.35499733688813034,
    mouthSmileRight: 0.35499733688813034,
  },
  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78341,
    browInnerUp: 0.452,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: {
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.351,
    mouthFunnel: 1,
    browInnerUp: 1,
  },
  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: {
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.5700000000000001,
    noseSneerRight: 0.51,
    eyeLookDownLeft: 0.39435766259644545,
    eyeLookUpRight: 0.4039761421719682,
    eyeLookInLeft: 0.9618479575523053,
    eyeLookInRight: 0.9618479575523053,
    jawOpen: 0.9618479575523053,
    mouthDimpleLeft: 0.9618479575523053,
    mouthDimpleRight: 0.9618479575523053,
    mouthStretchLeft: 0.27893590769016857,
    mouthStretchRight: 0.2885543872656917,
    mouthSmileLeft: 0.5578718153803371,
    mouthSmileRight: 0.38473918302092225,
    tongueOut: 0.9618479575523053,
  },
};

const corresponding = {
  // Rhubarb mouth shapes (A-H,X) mapped to Avaturn visemes.
  // A: closed (PBM) | B: slight open (KG) | C: open (AA) | D: wide (EH)
  // E: round (OH/UH) | F: FV | G: TH | H: sibilant (S/SH/CH/J) | X: rest
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_aa",
  D: "viseme_E",
  E: "viseme_O",
  F: "viseme_FF",
  G: "viseme_TH",
  H: "viseme_SS",
  X: "viseme_sil",
};

let setupMode = false;

const Model= ({audioRef}) => {
  const { nodes, materials, scene, animations: avatarAnimations = [] } = useGLTF("/models/avaturn-t2.glb");
  const { message, onMessagePlayed, chat, audioUnlocked} = useChat();
  const [lipsync, setLipsync] = useState();
  // const audioRef = useRef(null);

  useEffect(() => {

    if (!audioRef.current) {
      // audioRef.current = new Audio(); // Create audio instance once
      return;
    }

    //  // Initialize AudioContext once
    //  if (!audioContextRef.current) {
    //   audioContextRef.current = new (window.AudioContext || window.webkitAudioContext)();
    // }

    // console.log(message);
    if (!message) {
      setAnimation("Idle");
      return;
    }

    setAnimation(message.animation);
    setFacialExpression(message.facialExpression);
    const safeLipsync =
      message.lipsync && Array.isArray(message.lipsync.mouthCues)
        ? message.lipsync
        : null;
    setLipsync(safeLipsync);

    if (!message.audio || typeof message.audio !== "string") {
      console.error("Model: missing or invalid message.audio; skipping playback");
      return;
    }

    let audioURL;
    try {
      const bytes = Uint8Array.from(atob(message.audio), (c) => c.charCodeAt(0));
      const audioBlob = new Blob([bytes], { type: "audio/mpeg" });
      audioURL = URL.createObjectURL(audioBlob);
    } catch (e) {
      console.error("Model: failed to decode audio base64", e);
      return;
    }

    const audio = audioRef.current;
    audio.src = audioURL;
    audio.onended = onMessagePlayed;
    const playAudio = async () => {
      try {
        await audio.play();
        localStorage.setItem("audioUnlocked", "true"); // Save unlock state
      } catch (e) {
        console.warn("Autoplay blocked, waiting for user interaction");

        if (!audioUnlocked) {
          console.log("audio not unlocked)")
          const unlockAutoplay = async () => {
            try {
              await audio.play();
              localStorage.setItem("audioUnlocked", "true");
            } catch (err) {
              console.error("Playback error:", err);
            }
            window.removeEventListener("click", unlockAutoplay);
          };
          window.addEventListener("click", unlockAutoplay, { once: true });
        }
      }
    };
    if (audioUnlocked) {
      console.log("audio unlocked)")
      playAudio();
    } else {
      console.log("Waiting for user interaction to unlock audio");
    }
  }, [message, audioUnlocked, audioRef]);

  // Use the dedicated animation set (retargeted to this avatar).
  const { animations } = useGLTF("/models/animations.glb");
  const group = useRef();
  const { actions, mixer } = useAnimations(animations, group);
  const [animation, setAnimation] = useState(
    animations.find((a) => a.name === "Idle") ? "Idle" : (animations[0]?.name ?? "")
  );

  useEffect(() => {
    if (!animation) return;
    if (actions[animation]) {
      actions[animation]
        .reset()
        .fadeIn(mixer?.stats?.actions?.inUse === 0 ? 0 : 0.5)
        .play();
    }

    return () => {
      if (actions[animation]) {
        actions[animation].fadeOut(0.5);
      }
    };
  }, [animation, actions, mixer]);

  // Pick a mesh that contains the face morph targets for this avatar.
  const morphSource =
    nodes?.Head_Mesh ||
    nodes?.Eye_Mesh ||
    nodes?.Eyelash_Mesh ||
    nodes?.Body_Mesh;
  const morphDict = morphSource?.morphTargetDictionary || {};

  // Morph Target logic for facial expressions
  const lerpMorphTarget = (target, value, speed = 0.1) => {
    scene.traverse((child) => {
      if (child.isSkinnedMesh && child.morphTargetDictionary) {
        const index = child.morphTargetDictionary[target];
        if (
          index === undefined ||
          child.morphTargetInfluences[index] === undefined
        ) {
          return;
        }
        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index],
          value,
          speed
        );

        if (!setupMode) {
          try {
            set({
              [target]: value,
            });
          } catch (e) {}
        }
      }
    });
  };

  const [blink, setBlink] = useState(false);
  const [winkLeft, setWinkLeft] = useState(false);
  const [winkRight, setWinkRight] = useState(false);
  const [facialExpression, setFacialExpression] = useState("");
  const [audio, setAudio] = useState();

  const pickFirstExistingMorph = (candidates) => {
    for (const name of candidates) {
      if (morphDict && Object.prototype.hasOwnProperty.call(morphDict, name)) return name;
    }
    return null;
  };

  const blinkLeftKey = pickFirstExistingMorph([
    "eyeBlinkLeft",
    "EyeBlinkLeft",
    "blinkLeft",
    "BlinkLeft",
    "blink_L",
    "Blink_L",
  ]);
  const blinkRightKey = pickFirstExistingMorph([
    "eyeBlinkRight",
    "EyeBlinkRight",
    "blinkRight",
    "BlinkRight",
    "blink_R",
    "Blink_R",
  ]);

  useFrame(() => {
    const appliedMorphTargets = []; // Define the array here

    if (!setupMode) {
      Object.keys(morphDict).forEach((key) => {
        const mapping = facialExpressions[facialExpression];
        if (key === blinkLeftKey || key === blinkRightKey) {
          return; // Skip eye blink targets
        }
        if (mapping && mapping[key]) {
          lerpMorphTarget(key, mapping[key], 0.1);
        } else {
          lerpMorphTarget(key, 0, 0.1);
        }
      });

      // Handle eye blink separately
      if (blinkLeftKey) lerpMorphTarget(blinkLeftKey, blink || winkLeft ? 1 : 0, 0.5);
      if (blinkRightKey) lerpMorphTarget(blinkRightKey, blink || winkRight ? 1 : 0, 0.5);

      // LIPSYNC logic
      if (
        !setupMode &&
        message &&
        lipsync &&
        Array.isArray(lipsync.mouthCues) &&
        audioRef.current
      ) {
        const audio = audioRef.current;
        const currentAudioTime = audio.currentTime;

        if (currentAudioTime !== undefined) {
          // Faster "attack" makes consonants (M/B/P) actually close the mouth.
          const ACTIVE_VISEME_SPEED = 0.35;
          const RESET_VISEME_SPEED = 0.2;
          const VISEME_STRENGTH = {
            // Keep closures strong
            viseme_PP: 0.78,
            // Reduce vowel openness to show less teeth
            viseme_aa: 0.55,
            viseme_E: 0.6,
            viseme_I: 0.6,
            viseme_O: 0.6,
            viseme_U: 0.6,
            // Others
            viseme_kk: 0.75,
            // F/V “lip bite” — keep very soft (nearly off)
            viseme_FF: 0.15,
            viseme_TH: 0.75,
            viseme_SS: 0.7,
            viseme_sil: 0.9,
          };

          for (let i = 0; i < lipsync.mouthCues.length; i++) {
            const mouthCue = lipsync.mouthCues[i];
            if (
              currentAudioTime >= mouthCue.start &&
              currentAudioTime <= mouthCue.end
            ) {
              const morphName = corresponding[mouthCue.value];
              if (morphName && Object.prototype.hasOwnProperty.call(morphDict, morphName)) {
                appliedMorphTargets.push(morphName); // Add the morph target to the list
                const strength = VISEME_STRENGTH[morphName] ?? 0.85;
                lerpMorphTarget(
                  morphName,
                  strength,
                  morphName === "viseme_PP" ? 0.55 : ACTIVE_VISEME_SPEED
                ); // Apply morph target quickly
              }
              break;
            }
          }

          // Keep silence viseme down while speaking.
          if (appliedMorphTargets.length > 0 && Object.prototype.hasOwnProperty.call(morphDict, "viseme_sil")) {
            lerpMorphTarget("viseme_sil", 0, RESET_VISEME_SPEED);
          }
        }
      }

      // Reset other morph targets if not in the appliedMorphTargets list
      Object.values(corresponding).forEach((value) => {
        if (!appliedMorphTargets.includes(value)) {
          lerpMorphTarget(value, 0, 0.35); // Reset visemes faster for crisp closures
        }
      });
    }
  });

 
  

  useControls("FacialExpressions", {
    chat: button(() => chat()),
    winkLeft: button(() => {
      setWinkLeft(true);
      setTimeout(() => setWinkLeft(false), 300);
    }),
    winkRight: button(() => {
      setWinkRight(true);
      setTimeout(() => setWinkRight(false), 300);
    }),
    animation: {
      value: animation,
      options: animations.map((a) => a.name),
      onChange: (value) => setAnimation(value),
    },
    facialExpression: {
      options: Object.keys(facialExpressions),
      onChange: (value) => setFacialExpression(value),
    },
    enableSetupMode: button(() => {
      setupMode = true;
    }),
    disableSetupMode: button(() => {
      setupMode = false;
    }),
    logMorphTargetValues: button(() => {
      const emotionValues = {};
      Object.keys(morphDict).forEach((key) => {
        if (key === blinkLeftKey || key === blinkRightKey) {
          return; // eyes wink/blink are handled separately
        }
        const idx = morphDict[key];
        const value = morphSource?.morphTargetInfluences?.[idx];
        if (value > 0.01) {
          emotionValues[key] = value;
        }
      });
      console.log(JSON.stringify(emotionValues, null, 2));
    }),
  });

  const [, set] = useControls("MorphTarget", () =>
    Object.assign(
      {},
      ...Object.keys(morphDict).map((key) => {
        return {
          [key]: {
            label: key,
            value: 0,
            min: morphSource?.morphTargetInfluences?.[morphDict[key]] ?? 0,
            max: 1,
            onChange: (val) => {
              if (setupMode) {
                lerpMorphTarget(key, val, 1);
              }
            },
          },
        };
      })
    )
  );

  useEffect(() => {
    let blinkTimeout;
    const nextBlink = () => {
      blinkTimeout = setTimeout(() => {
        setBlink(true);
        setTimeout(() => {
          setBlink(false);
          nextBlink();
        }, 200);
      }, THREE.MathUtils.randInt(1000, 5000));
    };
    nextBlink();
    return () => clearTimeout(blinkTimeout);
  }, []);

  return (
    <group  ref={group} dispose={null}>
      <primitive object={nodes.Hips} />
      <skinnedMesh geometry={nodes.Body_Mesh.geometry} material={materials.Body} skeleton={nodes.Body_Mesh.skeleton} />
      <skinnedMesh geometry={nodes.avaturn_glasses_0.geometry} material={materials.avaturn_glasses_0_material} skeleton={nodes.avaturn_glasses_0.skeleton} />
      <skinnedMesh geometry={nodes.avaturn_glasses_1.geometry} material={materials.avaturn_glasses_1_material} skeleton={nodes.avaturn_glasses_1.skeleton} />
      <skinnedMesh geometry={nodes.avaturn_hair_0.geometry} material={materials.avaturn_hair_0_material} skeleton={nodes.avaturn_hair_0.skeleton} />
      <skinnedMesh geometry={nodes.avaturn_hair_1.geometry} material={materials.avaturn_hair_1_material} skeleton={nodes.avaturn_hair_1.skeleton} />
      <skinnedMesh geometry={nodes.avaturn_shoes_0.geometry} material={materials.avaturn_shoes_0_material} skeleton={nodes.avaturn_shoes_0.skeleton} />
      <skinnedMesh geometry={nodes.avaturn_look_0.geometry} material={materials.avaturn_look_0_material} skeleton={nodes.avaturn_look_0.skeleton} />
      <skinnedMesh
        name="Eye_Mesh"
        geometry={nodes.Eye_Mesh.geometry}
        material={materials.Eyes}
        skeleton={nodes.Eye_Mesh.skeleton}
        morphTargetDictionary={nodes.Eye_Mesh.morphTargetDictionary}
        morphTargetInfluences={nodes.Eye_Mesh.morphTargetInfluences}
      />
      <skinnedMesh
        name="EyeAO_Mesh"
        geometry={nodes.EyeAO_Mesh.geometry}
        material={materials.EyeAO}
        skeleton={nodes.EyeAO_Mesh.skeleton}
        morphTargetDictionary={nodes.EyeAO_Mesh.morphTargetDictionary}
        morphTargetInfluences={nodes.EyeAO_Mesh.morphTargetInfluences}
      />
      <skinnedMesh
        name="Eyelash_Mesh"
        geometry={nodes.Eyelash_Mesh.geometry}
        material={materials.Eyelash}
        skeleton={nodes.Eyelash_Mesh.skeleton}
        morphTargetDictionary={nodes.Eyelash_Mesh.morphTargetDictionary}
        morphTargetInfluences={nodes.Eyelash_Mesh.morphTargetInfluences}
      />
      <skinnedMesh
        name="Head_Mesh"
        geometry={nodes.Head_Mesh.geometry}
        material={materials.Head}
        skeleton={nodes.Head_Mesh.skeleton}
        morphTargetDictionary={nodes.Head_Mesh.morphTargetDictionary}
        morphTargetInfluences={nodes.Head_Mesh.morphTargetInfluences}
      />
      <skinnedMesh
        name="Teeth_Mesh"
        geometry={nodes.Teeth_Mesh.geometry}
        material={materials.Teeth}
        skeleton={nodes.Teeth_Mesh.skeleton}
        morphTargetDictionary={nodes.Teeth_Mesh.morphTargetDictionary}
        morphTargetInfluences={nodes.Teeth_Mesh.morphTargetInfluences}
      />
      <skinnedMesh
        name="Tongue_Mesh"
        geometry={nodes.Tongue_Mesh.geometry}
        material={materials.Teeth}
        skeleton={nodes.Tongue_Mesh.skeleton}
        morphTargetDictionary={nodes.Tongue_Mesh.morphTargetDictionary}
        morphTargetInfluences={nodes.Tongue_Mesh.morphTargetInfluences}
      />
    </group>
  )
}

useGLTF.preload('/models/avaturn-t2.glb')
useGLTF.preload("/models/animations.glb");
export default Model;